Adyen/adyen-hybris

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/checkout/steps/SelectPaymentMethodCheckoutStepController.java, adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon-beans.xml, adyenv6b2ccheckoutaddon/resources/localization/adyenv6b2ccheckoutaddon-locales_en.properties, adyenv6b2ccheckoutaddon/src/com/adyen/v6/populator/AbstractOrderPopulator.java, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/adyenv6core-spring.xml, adyenv6core/src/com/adyen/v6/actions/order/AdyenCheckAuthorizationAction.java, adyenv6core/src/com/adyen/v6/actions/order/AdyenCheckCaptureAction.java, adyenv6core/src/com/adyen/v6/commands/AdyenCaptureCommand.java, adyenv6core/src/com/adyen/v6/service/AdyenOrderService.java, adyenv6core/testsrc/com/adyen/v6/actions/order/AdyenCheckAuthorizationActionTest.java, adyenv6core/testsrc/com/adyen/v6/actions/order/AdyenCheckCaptureActionTest.java, adyenv6core/testsrc/com/adyen/v6/commands/AdyenCaptureCommandTest.java, adyenv6core/testsrc/com/adyen/v6/service/AdyenTransactionServiceTest.java, adyenv6ordermanagement/testsrc/com/adyen/v6/actions/returns/AdyenCaptureRefundActionTest.java
AVS Results
Card data (bin, holder, expiration)
Fraud Results
=> PW-128 Store API results after successful authorization

adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java
Add support for databases other than MySQL
=> PW-160 Make HPP optional

bin/custom/adyen/adyenCommerceServices/web/src/com/adyen/commerceservices/rest/AdyenNotificationReceiver.java, bin/custom/adyen/adyenServices/src/com/adyen/services/integration/data/PaymentMethod.java, bin/custom/adyen/adyenServices/src/com/adyen/services/strategy/impl/AbstractAdyenNotificationStrategy.java
handle multiple notificationitems
handle multiple transaction entries for notification processing
handle additional directory lookup response fields
=> Hybris 5.5 bugfixes

adyenv6ordermanagement/buildcallbacks.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement-spring.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process.6.0.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process.6.4.xml, adyenv6ordermanagement/src/com/adyen/v6/actions/returns/service/AdyenRefundAmountCalculationService.java
=> Separate order-process xml for Hybris versions

adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/service/DefaultAdyenNotificationService.java
Add unique identifier to AdyenNotificationItem
Receiving and processing notifications
=> Add unique identifier to AdyenNotificationItem

adyenv6core/src/com/adyen/v6/repository/NotificationItemRepository.java
Replaced hardcoded LIMIT 1000 in query with .setCount from FlexibleSearchQuery
Notifications processing
**Fixed issue**:  #66
=> PW-366: Replaced limit in query with .setCount from FlexibleSearchQuery

adyenv6b2ccheckoutaddon/src/com/adyen/v6/forms/validation/AdyenPaymentFormValidator.java
Use rememberdetails validator only in case of Credit Card
CC, APM checkout
=> Use rememberdetails validator only in case of Credit Card

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/resources/adyenv6core-spring.xml, adyenv6core/src/com/adyen/v6/converters/PaymentMethodConverter.java, adyenv6core/src/com/adyen/v6/factory/AdyenPaymentServiceFactory.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java
Payment method listing using Checkout API
Checkout PM listing
=> Payment method listing using Checkout API

adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java
=> Fixing merge issues on DefaultAdyenPaymentService

adyenv6b2ccheckoutaddon/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java
Show social security number only for OpenInvoice methods
**Test scenarios**
Checkout with delivery addresses in NL and SE
=> Show social security number only for OpenInvoice methods

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon.build.number, adyenv6b2ccheckoutaddon/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6b2ccheckoutaddon/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java, adyenv6backoffice/resources/adyenv6backoffice.build.number, adyenv6core/resources/adyenv6core.build.number, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/testsrc/com/adyen/v6/factory/AdyenRequestFactoryTest.java, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess.build.number, adyenv6ordermanagement/resources/adyenv6ordermanagement.build.number
Use resultCode for APMs
Fixed tests
Version bump to 4.0.1
authorisations with cc and alternatives
=> Use resultCode for APMs and tests fixes

adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java
=> [PW-985]: OCC Boleto issue Fix

adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java
=> [PW-1038]: Excluded bcmc_mobile_QR alternate payment method

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java
=>  [PW-1018]: Checkout component version upgrade to 2.1

adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java
[PW-1088] Hide wechatpayWeb and wechatpayQR
Add wechatpayWeb and wechatpayQR as payment methods and test if they are filtered
=> Hide all wechatpay and only show wechatpayWeb

adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon.build.number, adyenv6backoffice/resources/adyenv6backoffice.build.number, adyenv6core/resources/adyenv6core.build.number, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess.build.number, adyenv6ordermanagement/resources/adyenv6ordermanagement.build.number
Add boleto fields label in backoffice
=> Add labels for boleto fields in backoffice update version

adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java
=> [Pw-1351]: Oney (facilpay) support added

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/checkout/steps/SelectPaymentMethodCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/3ds2_payment.jsp, adyenv6backoffice/resources/adyenv6backoffice-backoffice-config.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/facades/AdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java
=> [PW-529]: Dynamic origin key support

README.md, adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon.build.number, adyenv6backoffice/resources/adyenv6backoffice.build.number, adyenv6core/resources/adyenv6core.build.number, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess.build.number, adyenv6notification/resources/adyenv6notification.build.number, adyenv6notification/web/src/com/adyen/v6/controllers/AdyenNotificationController.java, adyenv6ordermanagement/resources/adyenv6ordermanagement.build.number
=> Release 6.1.0

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/checkoutSummaryPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/css/adyenv6b2ccheckoutaddon.css, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js
Show spinner and disables the whole screen while the result from /placeOrder is not returned
=> [PW-1622] Show spinner while loading after "Place Order"

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/resources/test/SaleToPOIResponse.json, adyenv6core/resources/test/SaleToPOIResponseInProgress.json, adyenv6core/resources/test/SaleToPOIResponsePaymentCancelled.json, adyenv6core/resources/test/SaleToPOIResponseStatusCancelled.json, adyenv6core/resources/test/SaleToPOIResponseStatusResponseWithReceipt.json, adyenv6core/resources/test/SaleToPOIResponseWithReceipt.json, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/populator/AbstractOrderPopulator.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenOrderService.java, adyenv6core/src/com/adyen/v6/util/TerminalAPIUtil.java, adyenv6core/testsrc/com/adyen/v6/converters/PosPaymentResponseConverterTest.java, adyenv6core/testsrc/com/adyen/v6/facade/AdyenCheckoutFacadeTest.java, adyenv6core/testsrc/com/adyen/v6/factory/AdyenRequestFactoryTest.java, adyenv6core/testsrc/com/adyen/v6/util/TerminalAPIUtilTest.java
=> POS Payment Receipt Processing

adyenv6core/resources/adyenv6core-items.xml
=> [PW-2334]: API Key column resize

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/forms/AdyenPaymentForm.java, adyenv6core/src/com/adyen/v6/populator/CartPopulator.java
=> [PW-2465] : SEPA direct debit support

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/adyenv6core-spring.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/service/AdyenTransactionService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenTransactionService.java, adyenv6core/testsrc/com/adyen/v6/facade/AdyenCheckoutFacadeTest.java, adyenv6core/testsrc/com/adyen/v6/service/AdyenTransactionServiceTest.java
- Creating ON_HOLD order when REDIRECT_SHOPPER response is received
- Update payment info and order status when payment is completed or cancelled
=> PW-2524 - Update 3DS1 Order Flow

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/securedFieldsMethod.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js
=> [PW-2672]: Hide Remember me button when contract type is NONE

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java, adyenv6core/src/com/adyen/v6/facades/AdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/testsrc/com/adyen/v6/facade/AdyenCheckoutFacadeTest.java
- Create PENDING order before redirect
- Restore order if payment not authorised
- Unit tests
=> PW-2525 - Update 3ds2 flow

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/constants/AdyenControllerConstants.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java, adyenv6core/resources/adyenv6core-spring.xml, adyenv6core/src/com/adyen/v6/facades/AdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/testsrc/com/adyen/v6/facade/AdyenCheckoutFacadeTest.java
Restores the cart from order when new 3DS1/redirect flow has payment not authorised or other negative scenario
=> PW-2530 - Restore cart from order on negative scenario

adyenv6core/src/com/adyen/v6/actions/order/AdyenCheckAuthorizationAction.java, adyenv6core/src/com/adyen/v6/actions/order/AdyenCheckNewOrderAction.java, adyenv6core/src/com/adyen/v6/actions/order/AdyenCheckPendingOrderAction.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess/process/order-process-spring.xml, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess/process/order-process.1905.xml, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess/process/order-process.6.0.xml, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess/process/order-process.6.4.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process-spring.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process.1905.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process.6.0.xml, adyenv6ordermanagement/resources/adyenv6ordermanagement/process/order-process.6.4.xml
New flow will stop and wait for some minutes if the order is still on PAYMENT_PENDING status
=> Update fulfilment/order management process to include PAYMENT_PENDING status

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenComponentController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/checkout/steps/SelectPaymentMethodCheckoutStepController.java, adyenv6core/src/com/adyen/v6/facades/AdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenOrderService.java
…or handling in generic flows.
=> [PW-2709]: Paypal flow updated for early order creation. 

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenComponentController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/checkout/steps/SelectPaymentMethodCheckoutStepController.java
=> [PW-2642]: Fixed AdyenNonAuthorizedPaymentException log messages

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java
=> [PW-2919]  SameSite cookie Fix

adyenv6backoffice/resources/adyenv6backoffice-backoffice-config.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java
=> [PW-2943]: Tokenization for guest customer

adyenv6core/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java
- Class was deleted by mistake on https://github.com/Adyen/adyen-hybris/commit/f49d9ae44f7cf73d0c4a49b577cd04ea7ddc300c#diff-16886a3218a9754ccb86b0c6170cc397aa6cf33026ea588417d6aa3c581300a9
- Also fixed package name to reflect the one of the tested class
=> Restoring AdyenCheckoutFacadeTest

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/constants/AdyenControllerConstants.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/testsrc/com/adyen/v6/facades/AdyenCheckoutFacadeTest.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java, adyenv6core/testsrc/com/adyen/v6/factory/AdyenRequestFactoryTest.java
- Always pass customer object so data can be set on PaymentsRequest and passed to Klarna redirect
- Fixed redirect after payment error with guest shopper
Tested with Klarna and a few other redirect methods, also tested credit cards
=> PW-3134 - Klarna - fix for guest shoppers

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js
=> [PW-3383]: Fix invalid card error message

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/src/com/adyen/v6/commands/AdyenCaptureCommand.java, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java
=> [PW-3408]: Clearpay support added

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/checkout/steps/SelectPaymentMethodCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/checkoutSummaryPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6backoffice/resources/adyenv6backoffice-backoffice-config.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/resources/localization/adyenv6core-locales_en.properties, adyenv6core/src/com/adyen/v6/facades/AdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/service/AdyenPaymentService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenPaymentService.java
- Added clientKey field on backoffice
- Retrieve clientKey value and use it on component configurations
- Updated component version
Tested methods using components:
Cards, one-click cards, iDeal, EPS, Sepa, Paypal, MB Way
=> [PW-3572]: Updated components to use clientKey instead of originKey

adyenv6core/src/com/adyen/v6/service/AdyenNotificationService.java, adyenv6core/src/com/adyen/v6/service/DefaultAdyenNotificationService.java
- PENDING order, order already CANCELLED and order already AUTHORISED
=> [PW-3538]: Cancel pending orders after OFFER_CLOSED notification

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenComponentController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenSummaryCheckoutStepController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/messages/base.properties, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/messages/base_en.properties, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/checkoutOrderSummary.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/checkoutSummaryPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/css/adyenv6b2ccheckoutaddon.css, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/populator/CartPopulator.java
Apple Pay support in Hybris
Tested apple pay payment flow.
=> Pw 1549 Apple Pay support in Hybris

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/alternativeMethod.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/storedCardMethod.tag
Updated checkout payment method logo URL from PNG to SVG. This fixes icon for KCP as well.
=> [PW-3767] : Updated payment method logos from PNG to SVG

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/alternativeMethod.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/forms/AdyenPaymentForm.java, adyenv6core/src/com/adyen/v6/populator/CartPopulator.java
Added AfterPay payment method.
Tested payment flow using AfterPay
=> PW-3785 Added AfterPay support in Hybris

README.md, adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon.build.number, adyenv6backoffice/resources/adyenv6backoffice.build.number, adyenv6core/resources/adyenv6core.build.number, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6fulfilmentprocess/resources/adyenv6fulfilmentprocess.build.number, adyenv6notification/resources/adyenv6notification.build.number, adyenv6ordermanagement/resources/adyenv6ordermanagement.build.number
Updated version to 9.2.0 and added AfterPay in docs.
=> Bump version to 9.2.0

README.md, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/forms/validation/AdyenPaymentFormValidator.java
Added configuration "isCardHolderNameRequired" to make card holder name field mandatory or not.
Credit card payment with and without card holder name.
=> PW-3903 Added configuration "isCardHolderNameRequired" for Credit card holder name

README.md, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/alternativeMethod.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/methodSelector.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/forms/AdyenPaymentForm.java, adyenv6core/src/com/adyen/v6/populator/CartPopulator.java
Pass brand value for Gift Card
Gift card flow
=> PW-4417 Pass brand value for giftcard

adyenv6core/src/com/adyen/v6/commands/AdyenCaptureCommand.java
Fixed capture response check.
Cleaned up deprecated methods.
Payment flow with automatic & manual capture
**Fixed issue**:  #248
=> PW-4741 Fixed response check for capture

adyenv6core/src/com/adyen/v6/repository/NotificationItemRepository.java
MerchantReference can be null for notifications of type REPORT_AVAILABLE, that causes failure on `isNewerNotificationExists` check 
Fixes #234
=> Added check for merchantReference == null when processing notifications

adyenv6b2ccheckoutaddon/resources/adyenv6b2ccheckoutaddon-spring.xml, adyenv6b2ccheckoutaddon/src/com/adyen/v6/acceleratorfacades/flow/impl/AdyenCheckoutFlowFacade.java
Removed unnecessary **hasNoPaymentInfo** method overriding
Relates to #210
=> Small refactor to AdyenCheckoutFlowFacade

adyenv6b2ccheckoutaddon/acceleratoraddon/web/src/com/adyen/v6/controllers/pages/AdyenComponentController.java, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/checkoutOrderSummary.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/checkoutSummaryPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/resources/adyenv6core-beans.xml, adyenv6core/resources/adyenv6core-items.xml, adyenv6core/src/com/adyen/v6/commands/AdyenCaptureCommand.java, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/populator/CartPopulator.java
- Added support to Amazon Pay using checkout component
- Added check to render button only for current view (web or mobile)
- Amazon pay success and failure scenarios
- Retested some previous implemented components that could be impacted by changes (paypal, google pay)
- Retested credit cards and other redirect methods
(tests on both web and mobile views)
=> PW-3776 - Added support to Amazon Pay

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/messages/base.properties, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/messages/base_en.properties, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/messages/base_pt.properties, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/tags/responsive/alternativeMethod.tag, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/selectPaymentMethodPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java, adyenv6core/src/com/adyen/v6/facades/DefaultAdyenCheckoutFacade.java, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java, adyenv6core/src/com/adyen/v6/forms/validation/AdyenPaymentFormValidator.java
Added **PayBright** payment method.
PayBright success & failure scenarios. Sanity tested other payment methods.
=> PW-5001 Added support for PayBright payment method

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js, adyenv6core/src/com/adyen/v6/factory/AdyenRequestFactory.java
Set card brand as payment method for one click cards
Visa, master card, dual branded cards etc.
=> PE-138 Set card brand as payment method for one click cards

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js
Fixed ApplePay bug
ApplePay payment flow
=> PE-184 Fixed ApplePay bug

adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/WEB-INF/views/responsive/pages/checkout/multi/checkoutSummaryPage.jsp, adyenv6b2ccheckoutaddon/acceleratoraddon/web/webroot/_ui/responsive/common/js/adyen.checkout.js
Fixed Paypal auth flow error
PayPal Sale and Capture flow.
=> PE-223 Fixed Paypal auth flow error

adyenv6core/src/com/adyen/v6/constants/Adyenv6coreConstants.java
=> Update connector version
